### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Theo-Dancoisne** [MartinPAVY/responsiveTP#1]
est-ce que tu dois aussi faire le contenu du menu ?
et est-ce que le prof est d'acord pour que l'on copie le site (font, size, color, ...) ou alors il veut que l'on reste dans un wireframe sans s'occuper des couleurs et du style du texte ?

**Comment by MartinPAVY** [comment]
Concernant contenu du menu, tu parles de quoi? 
Color oui on peut, Font dans l'idée mais si c'est pas la même c'est pas grave, faut juste éviter le times new roman si le site est en arial quoi. Et Size c'est dans l'idée aussi, faut pas faire identique mais faut que ça reste ressemblant.
C'est une maquette donc c'est a mi chemin entre le wireframe et une copie du site
